typography_spectrum: 0.5150376
color:
  saturation: 0.6750805
  brandStrength: 0
  lightness: 0.5912997
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#b9ccd2'
    - '#2c2b31'
    - '#5d7077'
  rhythmicContrast: 0.2529538
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2293233
analytics:
  twitter: null
  google: null
  facebook: null
name: hipstaMB
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Pekarna
    id: f2f6cc6a-b80f-49df-b2d0-793a3ae0ec1d
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: soft HDR scoop of Maribor
purpose: []
