typography_spectrum: 0.5150376
color:
  saturation: 0.6750805
  brandStrength: 0
  lightness: 0.5912997
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#b9ccd2'
    - '#2c2b31'
    - '#5d7077'
  rhythmicContrast: 0.2529538
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2293233
analytics:
  twitter: null
  google: null
  facebook: null
name: hipstaMB
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Rainy day
    id: c23ed500-253c-450d-a8eb-f63977ef5c19
    type: content
  - name: Sunny day
    id: c2e4b43b-a035-46f5-982e-b2f7db8f1742
    type: content
  - name: Foggy day
    id: 9b4cb3d0-b915-417b-9f31-5f3d5f7ece31
    type: content
  - name: Pekarna
    id: f2f6cc6a-b80f-49df-b2d0-793a3ae0ec1d
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: HDR scoop of Maribor
description: hipstamatic/instagram
purpose: []
