name: hipstaMB
favicon: null
layout_spectrum: 0.20296
typography_spectrum: 0.90074
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#04cefe'
    - '#0a0603'
    - '#ad8144'
    - '#e00004'
  brandStrength: 0.1658118655905128
  lightness: 0.7739285146817565
  saturation: 0.625
  rhythmicContrast: 0.3909074896946549
purpose: []
