name: hipstaMB
favicon: null
layout_spectrum: 0
typography_spectrum: 0.509667
title: soft HDR scoop of Maribor
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2FBFF'
    - '#77E9FF'
    - '#04CFFF'
    - '#E9BD91'
    - '#160E04'
  brandStrength: 0
  lightness: 0.8286788
  saturation: 0.9618689
  rhythmicContrast: 0.7352309
purpose: []
