name: hipstaMB
favicon: null
layout_spectrum: 0.2476
typography_spectrum: 0.42126
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: soft HDR scoop of Maribor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#04cefe'
    - '#0a0603'
    - '#ad8144'
    - '#e00004'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
